name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    env:
      ELECTRON_CONFIG_CACHE: $HOME/.cache/electron

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.OS }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint Types
        run: yarn lint:types

      - name: Lint Source
        run: yarn lint:source

      - name: Lint Formatting
        run: yarn lint:format

      - name: Lint Styled
        run: yarn lint:styles

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    env:
      ELECTRON_CONFIG_CACHE: $HOME/.cache/electron

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.OS }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn test --coverage --maxWorkers=2

      - name: Upload Coverage
        uses: codecov/codecov-action@v1
