name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 14.16.0
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Lint Types
        run: yarn lint:types

      - name: Lint Source
        run: yarn lint:source

      - name: Lint Formatting
        run: yarn lint:prettier

      - name: Lint Styled
        run: yarn lint:styles

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 14.16.0
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Test
        run: yarn test --coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v1

  e2e:
    name: E2E
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 14.16.0
        os:
          - ubuntu-latest

    env:
      ELECTRON_CACHE: $HOME/.cache/electron
      ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: yarn test:e2e
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test:e2e
